### ISSUE TITLE
Occasional downtime of ROB server

### ISSUE THREAD

**Issue by pjiggens** [Helioviewer-Project/JHelioviewer-SWHV#107]
It seems that all ROB data cannot be loaded and I cannot access swhv.oma.be. I can load the initial 2 days of data from other servers (e.g. IAS) but after this I get the following JPIP error:
Socket timeout
Socket timeout while requesting JPIP URL

Is something being updated? Or something is broken?
I tried last week and had similar (the same) problems.

**Comment by bogdanni** [comment]
There is a software related occasional lockup of the ROB server which requires the reboot at the level of the virtual infrastructure. Sometimes it takes a little until the service is re-established because it involves several manual interventions. At this moment, the ROB services should be up.

Renaming the issue and keeping it open until the full migration to the new server is completed.

**Comment by bogdanni** [comment]
The ROB server has been solid since a few years; possibly due to changes in the virtual infrastructure.
