### ISSUE TITLE
Problem requesting long time series: server error ROB

### ISSUE THREAD

**Issue by dmueller3000** [Helioviewer-Project/JHelioviewer-SWHV#110]
Tried requesting AIA 171 time series from ROB server, from 2017-03-24 to 2018-03-26, cadence 6 hours. The goal was to check what happens when the user requests > 1000 frames. Instead of one of the expected behaviours (either retrieve all frames, or resample to stay below a given max. number of frames), an error message was returned.
<img width="1276" alt="Screen Shot 2019-03-26 at 09 40 31" src="https://user-images.githubusercontent.com/9073862/55001840-c26c0c00-4fd5-11e9-8b08-c162e193b8bd.png">

**Comment by bogdanni** [comment]
There are many reasons for server side failure, some of which cannot be returned to the user due to the design of the system. In this case, the JPIP server cannot find the assembled JPX file, which does not exist for unknown reasons.

**Comment by bogdanni** [comment]
ROB server suffers inexplicable segfaults, example below. The migration to the new server is stalling since 1.5 years.

Mar 26 10:42:10 2019] fits2fits.py[21422]: segfault at 7ff561ae4168 ip 00007ff56b6c7db3 sp 00007fff1385b270 error 4 in ld-2.11.3.so[7ff56b6ba000+1e000]
[Tue Mar 26 10:42:18 2019] fits2fits.py[21454]: segfault at 7fbded937168 ip 00007fbdf751adb3 sp 00007fff45c18150 error 4 in ld-2.11.3.so[7fbdf750d000+1e000]
[Tue Mar 26 10:42:22 2019] fits2fits.py[21474]: segfault at 7f870f66a168 ip 00007f871924ddb3 sp 00007fff77504650 error 4 in ld-2.11.3.so[7f8719240000+1e000]
[Tue Mar 26 10:42:23 2019] fits2fits.py[21486]: segfault at 7f4c01193168 ip 00007f4c0ad76db3 sp 00007fff1375c950 error 4 in ld-2.11.3.so[7f4c0ad69000+1e000]
[Tue Mar 26 10:47:34 2019] python[21843]: segfault at 7f7e071b5168 ip 00007f7e11fbcdb3 sp 00007fff4cb15b50 error 4 in ld-2.11.3.so[7f7e11faf000+1e000]
[Tue Mar 26 10:51:55 2019] fits2fits.py[21974]: segfault at 7f9159078dc0 ip 00007f91656e7e03 sp 00007fff01524780 error 4 in ld-2.11.3.so[7f91656da000+1e000]
[Tue Mar 26 10:52:18 2019] fits2fits.py[22074]: segfault at 7f4eca934168 ip 00007f4ed4517db3 sp 00007fff9736c920 error 4 in ld-2.11.3.so[7f4ed450a000+1e000]
[Tue Mar 26 10:52:20 2019] fits2fits.py[22084]: segfault at 7f0c893b5e28 ip 00007f0c94b77e03 sp 00007fff2cd0cec0 error 4 in ld-2.11.3.so[7f0c94b6a000+1e000]
[Tue Mar 26 10:52:38 2019] fits2fits.py[22153]: segfault at 7f246c4dae28 ip 00007f2477c9ce03 sp 00007fff0bc00420 error 4 in ld-2.11.3.so[7f2477c8f000+1e000]
[Tue Mar 26 10:53:05 2019] fits2fits.py[22264]: segfault at 7ffc4f573dc0 ip 00007ffc5bbe2e03 sp 00007fffd6bfc500 error 4 in ld-2.11.3.so[7ffc5bbd5000+1e000]
[Tue Mar 26 10:53:16 2019] fits2fits.py[22313]: segfault at 7fe2778e4168 ip 00007fe2814c7db3 sp 00007fffb4073570 error 4 in ld-2.11.3.so[7fe2814ba000+1e000]
[Tue Mar 26 10:53:17 2019] fits2fits.py[22318]: segfault at 7fbec1155168 ip 00007fbecad38db3 sp 00007fff787ce590 error 4 in ld-2.11.3.so[7fbecad2b000+1e000]
[Tue Mar 26 11:18:42 2019] python[2147]: segfault at 7fa556bb2168 ip 00007fa5619b9db3 sp 00007fff21ed3660 error 4 in ld-2.11.3.so[7fa5619ac000+1e000]
[Tue Mar 26 11:41:35 2019] fits2fits.py[4578]: segfault at 7f2acba27168 ip 00007f2ad560adb3 sp 00007fffdb9b5760 error 4 in ld-2.11.3.so[7f2ad55fd000+1e000]
[Tue Mar 26 11:41:47 2019] fits2fits.py[4639]: segfault at 7fb8751aee28 ip 00007fb880970e03 sp 00007fff7bcc5140 error 4 in ld-2.11.3.so[7fb880963000+1e000]
[Tue Mar 26 11:42:40 2019] fits2fits.py[4903]: segfault at 7f8c89073e28 ip 00007f8c94835e03 sp 00007fff783a7f50 error 4 in ld-2.11.3.so[7f8c94828000+1e000]
[Tue Mar 26 11:46:55 2019] python[5142]: segfault at 7f13807e3168 ip 00007f138b5eadb3 sp 00007fff55d7e2d0 error 4 in ld-2.11.3.so[7f138b5dd000+1e000]
[Tue Mar 26 11:47:17 2019] fits2fits.py[5152]: segfault at 7f465a273168 ip 00007f4663e56db3 sp 00007fff728a8160 error 4 in ld-2.11.3.so[7f4663e49000+1e000]
[Tue Mar 26 11:47:21 2019] python[5158]: segfault at 7f476ba85168 ip 00007f477688cdb3 sp 00007fff025b5830 error 4 in ld-2.11.3.so[7f477687f000+1e000]
[Tue Mar 26 11:52:23 2019] fits2fits.py[5434]: segfault at 7f83f8c44dc0 ip 00007f84052b3e03 sp 00007fffb46031a0 error 4 in ld-2.11.3.so[7f84052a6000+1e000]
[Tue Mar 26 11:52:33 2019] fits2fits.py[5478]: segfault at 7fa37e03be28 ip 00007fa3897fde03 sp 00007fffb03da1a0 error 4 in ld-2.11.3.so[7fa3897f0000+1e000]
[Tue Mar 26 11:52:42 2019] fits2fits.py[5514]: segfault at 7ff652e9d168 ip 00007ff65ca80db3 sp 00007fffe0193090 error 4 in ld-2.11.3.so[7ff65ca73000+1e000]
[Tue Mar 26 11:52:51 2019] fits2fits.py[5558]: segfault at 7fabb1250e28 ip 00007fabbca12e03 sp 00007fffb822f720 error 4 in ld-2.11.3.so[7fabbca05000+1e000]
[Tue Mar 26 11:53:13 2019] fits2fits.py[5654]: segfault at 7f1fefde4e28 ip 00007f1ffb5a6e03 sp 00007fff6bce0df0 error 4 in ld-2.11.3.so[7f1ffb599000+1e000]
[Tue Mar 26 12:06:18 2019] fits2fits.py[6105]: segfault at 7f5752944168 ip 00007f575c527db3 sp 00007fff57b72b30 error 4 in ld-2.11.3.so[7f575c51a000+1e000]
[Tue Mar 26 12:07:11 2019] fits2fits.py[6167]: segfault at 7f02d4658168 ip 00007f02de23bdb3 sp 00007fff175da5b0 error 4 in ld-2.11.3.so[7f02de22e000+1e000]
[Tue Mar 26 12:07:14 2019] python[6173]: segfault at 7fcc5aca2168 ip 00007fcc65aa9db3 sp 00007fff3562b4c0 error 4 in ld-2.11.3.so[7fcc65a9c000+1e000]
[Tue Mar 26 12:18:39 2019] hv_jp2_transcod[6655]: segfault at 7f854794b168 ip 00007f8552ea9db3 sp 00007fff810865c0 error 4 in ld-2.11.3.so[7f8552e9c000+1e000]
[Tue Mar 26 12:20:17 2019] python[7677]: segfault at 7f4dccd41168 ip 00007f4dd7b48db3 sp 00007fffa40e8b20 error 4 in ld-2.11.3.so[7f4dd7b3b000+1e000]
[Tue Mar 26 12:21:43 2019] hv_jp2_transcod[7920]: segfault at 7f86938ee168 ip 00007f869ee4cdb3 sp 00007fffc4c9f420 error 4 in ld-2.11.3.so[7f869ee3f000+1e000]
[Tue Mar 26 12:21:50 2019] python[8359]: segfault at 7f7307ef4168 ip 00007f7312cfbdb3 sp 00007fffdb3c4c10 error 4 in ld-2.11.3.so[7f7312cee000+1e000]
[Tue Mar 26 12:23:22 2019] python[9027]: segfault at 7fe323bf9168 ip 00007fe32ea00db3 sp 00007fff9f54f340 error 4 in ld-2.11.3.so[7fe32e9f3000+1e000]
[Tue Mar 26 12:26:18 2019] python[9123]: segfault at 7fb9118d3168 ip 00007fb91c6dadb3 sp 00007fffaad93600 error 4 in ld-2.11.3.so[7fb91c6cd000+1e000]
[Tue Mar 26 12:26:55 2019] python[9133]: segfault at 7f53550eb168 ip 00007f535fef2db3 sp 00007fffa9b4ce70 error 4 in ld-2.11.3.so[7f535fee5000+1e000]
[Tue Mar 26 12:36:56 2019] python[9326]: segfault at 7fe53f56f168 ip 00007fe54a376db3 sp 00007fffe1c9b620 error 4 in ld-2.11.3.so[7fe54a369000+1e000]
[Tue Mar 26 12:41:44 2019] fits2fits.py[9590]: segfault at 7f5664334168 ip 00007f566df17db3 sp 00007fff3e905c70 error 4 in ld-2.11.3.so[7f566df0a000+1e000]
[Tue Mar 26 12:41:52 2019] fits2fits.py[9638]: segfault at 7f0c4a63ae28 ip 00007f0c55dfce03 sp 00007fff89616d30 error 4 in ld-2.11.3.so[7f0c55def000+1e000]
[Tue Mar 26 12:42:07 2019] fits2fits.py[9719]: segfault at 7f57d047a168 ip 00007f57da05ddb3 sp 00007ffff1039260 error 4 in ld-2.11.3.so[7f57da050000+1e000]
[Tue Mar 26 12:42:26 2019] fits2fits.py[9818]: segfault at 7fa8554ebe28 ip 00007fa860cade03 sp 00007fffa2313790 error 4 in ld-2.11.3.so[7fa860ca0000+1e000]
[Tue Mar 26 12:42:38 2019] fits2fits.py[9878]: segfault at 7fc655941e28 ip 00007fc661103e03 sp 00007fff5e8b3c10 error 4 in ld-2.11.3.so[7fc6610f6000+1e000]
[Tue Mar 26 12:43:17 2019] python[9986]: segfault at 7f874f1ff168 ip 00007f875a006db3 sp 00007fff8e1ca550 error 4 in ld-2.11.3.so[7f8759ff9000+1e000]
[Tue Mar 26 12:46:17 2019] python[10084]: segfault at 7f5539cef168 ip 00007f5544af6db3 sp 00007fff267d1130 error 4 in ld-2.11.3.so[7f5544ae9000+1e000]
[Tue Mar 26 12:51:54 2019] fits2fits.py[10264]: segfault at 7f552f3a4e28 ip 00007f553ab66e03 sp 00007fff959a6460 error 4 in ld-2.11.3.so[7f553ab59000+1e000]
[Tue Mar 26 12:51:54 2019] fits2fits.py[10265]: segfault at 7f56d8e0be28 ip 00007f56e45cde03 sp 00007fff90665ae0 error 4 in ld-2.11.3.so[7f56e45c0000+1e000]
[Tue Mar 26 12:52:04 2019] fits2fits.py[10309]: segfault at 7f5bafb47dc0 ip 00007f5bbc1b6e03 sp 00007fffccb0b800 error 4 in ld-2.11.3.so[7f5bbc1a9000+1e000]
[Tue Mar 26 12:52:17 2019] fits2fits.py[10365]: segfault at 7fc428371168 ip 00007fc431f54db3 sp 00007fffa87ae6d0 error 4 in ld-2.11.3.so[7fc431f47000+1e000]
[Tue Mar 26 12:52:31 2019] fits2fits.py[10425]: segfault at 7f6902c47168 ip 00007f690c82adb3 sp 00007fff91eeee00 error 4 in ld-2.11.3.so[7f690c81d000+1e000]
[Tue Mar 26 12:52:45 2019] fits2fits.py[10489]: segfault at 7ff712377168 ip 00007ff71bd82db3 sp 00007fff6a3b6450 error 4 in ld-2.11.3.so[7ff71bd75000+1e000]

**Comment by bogdanni** [comment]
The server will hopefully be entirely replaced in the future.
