### ISSUE TITLE
JHV does not load default state at start-up when using IAS server

### ISSUE THREAD

**Issue by dmueller3000** [Helioviewer-Project/JHelioviewer-SWHV#174]
JHV does not load default state at start-up when using IAS server. I created a custom file to load the last 48h of AIA171 and selected this as default state in the Preferences, but it has no effect.

[state_IAS_AIA171_past48h.jhv.zip](https://github.com/Helioviewer-Project/JHelioviewer-SWHV/files/7208725/state_IAS_AIA171_past48h.jhv.zip)
.

**Comment by bogdanni** [comment]
Confirmed.

**Comment by helioshk** [comment]
The issue appears to be independent from the selected server.

**Comment by bogdanni** [comment]
I investigated this at the time of filing the issue, but didn't report back, sorry.

This is what happens: the default state is loaded *after* all image data sources (i.e., the [getDataSources](https://api.helioviewer.org/docs/v2/api/api_groups/official_clients.html#getdatasources) API call) are loaded. This in order to ensure that the server for which a particular dataset of the state file may refer to is up.

What happens is that some servers, in particular GSFC Beta and ESAC, are often down. Since the original version of this program, if there is a network error in the `getDataSources` call, it is retried indefinitely every 15 seconds and this behavior
was [preserved](https://github.com/Helioviewer-Project/JHelioviewer-SWHV/blob/09da9079a4cfafbef6e941005350976a86be497c/src/org/helioviewer/jhv/io/LoadSources.java#L52) throughout the rewrite of the code. 

In consequence, this activity never ends and therefore the default state is never loaded. At the instant I write this, all servers are up and the loading of default state succeeds.

Another consequence of this behavior is, if the URL of the `getDataSources` API call changes (like it happened when the ROB server was re-installed), old clients - simply by staying open - will continue requesting to wrong URL and filling the HTTP server's error log with noise. We had to resort to modify our server to return an empty response to requests for the old URL.

What I'm going to do is to remove the loop and let the request fail. I will add a menu item to refresh the data sources list in case the user started JHV without network and expects to continue to use it after the network connection is re-established.
