### ISSUE TITLE
Event metadata: wavelength number without unit (and potentially incorrect)

### ISSUE THREAD

**Issue by dmueller3000** [Helioviewer-Project/JHelioviewer-SWHV#18]
See attached screenshot: For SPoCA Active Regions, "mean wavelength" is listed as "1.71E-6", without units. I believe the number stems from the 171 Angstroem AIA channel, which would translate to 0.171E-6 m. Similarly for NOAA Active regions: Here, the number listed is "5E-5" - and I am unsure what this corresponds to. I understand that metadata provided by external servers not necessarily comes with the appropriate units, but it would be great if it could be formatted to provide clear information to the users. Thanks!

![screen shot 2016-06-28 at 13 47 10](https://cloud.githubusercontent.com/assets/9073862/16417937/18dded36-3d48-11e6-8afa-7bba901b13db.png)

**Comment by bogdanni** [comment]
In the HEK event description it comes as string "1.70999999227206E-6" and the unit appears to be indicated by parameter "obs wavelunit" as cm (found in "All Parameters"), thus 1.71E-6 seems correct by my reckoning (it indicates obviously the 17.1nm bandpass of AIA). No idea why HEK uses such a unit for wavelength. Similarly for NOAA ARs, 5E-5 (raw string "4.999999873689376E-5") corresponds to the visible 500nm. We felt this is an important parameter to distinguish between ARs detected in EUV and in visible wavelengths.

The raw string is weird probably because at a certain stage the parameter was stored by HEK with the loss of precision of a binary floating point number. We beautify it by rounding.
