### ISSUE TITLE
No To Placing Exports in the Temp folder!

### ISSUE THREAD

**Issue by simplio** [Helioviewer-Project/JHelioviewer-SWHV#189]
Why and who's idea was it to place exports into the User Temp directory? NO! Put it back or gives us the option where to save exports! That temp folder gets cleared way too often! (Version 4.3.0.10619)

NO!
C:\Users\username\AppData\Local\Temp\JHelioviewer-SWHV\Exports

YES!
C:\Users\username\JHelioviewer-SWHV\Exports

**Comment by bogdanni** [comment]
Sorry to bother you, this was in response to #188: the app stores other things in that directory like caches and libraries to be loaded at runtime. Those last ones were causing problems for non-ASCII usernames due to schizophrenic nature of Windows.

Searching around a bit, it does seem that Windows sometimes may clean that directory: https://superuser.com/questions/318497/do-files-in-the-temporary-folders-get-automatically-deleted
That may not be a bad idea if the user runs low on disk space.

I will separate the transient files to the User Temp directory and keep the rest in the usual location.

**Comment by bogdanni** [comment]
So, for the time being, I placed only the Cache and Downloads directories in the user temp directory (`C:\Users\$USER\AppData\Local\Temp\`), the rest in the usual location (`C:\Users\$USER\JHelioviewer-SWHV`).

The issue is: if the user directory contains non-ASCII characters, Windows (at least version 8.1) uses "code pages" which introduce discrepancies between the Java strings and the filenames as seen by the C libraries which need to use those files. This should not happen on other operating systems since POSIX forbids non-ASCII user names.

The solution with the user temp directory (this directory is treated in a special way by Windows) was the only one I found after spending a ton of time already on this Windows idiosyncrasy.

**Comment by bogdanni** [comment]
On my Mac, the program works when replacing `o` (Latin Small Letter O) in `JHelioviewer` with `ο` (Greek Small Letter Omicron). This #188 issue is purely a Windows problem.

I will release tomorrow version 4.3.1 with this directory split on Windows, although I strongly dislike it.
