### ISSUE TITLE
All capital "I"s appear in red(!)

### ISSUE THREAD

**Issue by pjiggens** [Helioviewer-Project/JHelioviewer-SWHV#192]
I think this may be a windows issue but all capital "I"s in jHV come out as red vertical bars (I don't think they are even "I"s

![image](https://user-images.githubusercontent.com/23653159/149914635-43083b48-2b4a-481d-922a-f5adeb2abca2.png)

**Comment by bogdanni** [comment]
What Windows version?

I think this is a font smoothing issue: Windows uses (or used) an algorithm that employs the individual R, G, B signals. A side effect are color fringes and may work badly with the font scaling Windows feature. The "I"s seem snapped on the R sub-pixel.

Could you please turn off font smoothing to verify this is the case? If it is, there is a ClearType setting somewhere which adjusts how the algorithm works.

The provider of Java also changed on Windows to be the JetBrains runtime which has "improvements" for font rendering. This was done to make the program run on "non-Western" localized versions of Windows. I'm still trying to get it to work with the regular Java runtime.

**Comment by pjiggens** [comment]
Windows 10 Enterprise Version 21H1
I tried to turn off the font smoothing (Value data 2 -> 0) and it didn't change. I restarted JHV but not windows as this should not be required but I can try that if you think it wise.
![image](https://user-images.githubusercontent.com/23653159/150093141-1fcb386c-df67-4554-9ccd-f8436bb30fe7.png)

**Comment by bogdanni** [comment]
That's a brutal way to change font smoothing 😄, there is a setting in the control panel. It didn't take effect because the fonts are still smoothed in the screenshot.

In any case, could you please try installing http://swhv.oma.be/download_test/JHelioviewer_4_3_2.exe ?
It reverts to a more regular version of the Java runtime. Could you pleas then post another screenshot like the first one in the thread, thanks!

**Comment by pjiggens** [comment]
![image](https://user-images.githubusercontent.com/23653159/150140846-47d994df-5827-48e3-b9eb-f7cc668c8ff7.png)

Problem has disappeared for now - closing...

**Comment by bogdanni** [comment]
You didn't show the "I" in AIA and HMI... So it was indeed the JetBrains runtime whose font rendering provoked the "I" to snap on the red sub-pixel.

I will leave here a comment because this issue is very puzzling:
- A user reported crash in #188.
- Since I cannot read Greek, I tried with Romanian Windows 8.1.
- I created user "țanțoș" with non-ASCII characters, note it uses [T-comma](https://en.wikipedia.org/wiki/T-comma) and [S-comma](https://en.wikipedia.org/wiki/S-comma), not to be confused with the variants of those letters with cedilla which are in the [Windows-1250](https://en.wikipedia.org/wiki/Windows-1250) code page used by Java. The Wikipedia pages of those letters mentions the past confusion about support for those variants of characters in software.
- Like mentioned in https://github.com/Helioviewer-Project/JHelioviewer-SWHV/issues/188#issuecomment-1010465606, I could not even reach the point the user reached: Java cannot even find the native libraries it needs to load.
- If I switch to JetBrains runtime, Java can load those libraries, I still don't understand why, possibly by doing a substitution.
- There is still the problem with character representation mismatching between Java and the native libraries (SPICE and Kakadu). Those libraries cannot find the files given to them by Java; ultimately, two directories, Cache and Downloads, from JHV directories are moved to the user temporary directory (`C:\Users\$USER\AppData\Local\Temp\`) after a user complains in #189 about the entire JHV directory being moved to the temporary directory.
- JetBrains runtime has "improvements" for font rendering which lead to this issue (#192) under some variations of resolution and version of Windows.
- Switching back to a regular Java runtime solves the font rendering, but breaks the loading of native libraries for user "țanțoș" (which means haughty or bumptious, btw). A new user "ăî" has no issue.

Conclusion: the regular Java runtime and those two directories in user temporary directory are believed to be working correctly for all languages, except for Romanian users with names containing "latin letter t and s with comma below" (and possibly user names of other languages with a similar confusion about letters).
