### ISSUE TITLE
JHelioviewer crashes

### ISSUE THREAD

**Issue by helioshk** [Helioviewer-Project/JHelioviewer-SWHV#199]
Hi,
Since I've updated to 4.3.2 I experience random crashes several times per day. 
Here is a full log of such an event:
http://94.130.58.182/temp/jhelio-dump.log

**Comment by bogdanni** [comment]
Those occur in the native library that decodes the JPEG2000 data and are very difficult to diagnose.
I don't see anything that changed which could trigger those.

In case it's due to the Java runtime environment, I prepared http://swhv.oma.be/download_test/JHelioviewer_4_3_2_amd64.deb which uses the OpenJDK instead of JetBrains.
It will not play very nice with Gnome HiDPI, but KDE should be OK.

Could you please try it out?

**Comment by helioshk** [comment]
I'm using XFCE.
Will try it, thank you!

**Comment by helioshk** [comment]
During 24 hours of intensive use, the new version didn't crash.

**Comment by bogdanni** [comment]
OK, the JRE track sounds plausible. From now on, Linux packages will be distributed again with OpenJDK JRE.

GNOME users will have to start it with `jhelioviewer -J-Dsun.java2d.uiScale=2.0`, or whatever pixel scaling their environment uses.
