### ISSUE TITLE
Missing timeline layers

### ISSUE THREAD

**Issue by pjiggens** [Helioviewer-Project/JHelioviewer-SWHV#270]
I was trying to view images with X-ray flux but the timeline layers appear to return no Groups/datasets to choose from.
![image](https://github.com/Helioviewer-Project/JHelioviewer-SWHV/assets/23653159/5af04e17-e387-493b-9326-1cbd8c1062f0)
As I thought this may be a version issue (our approved software is still on v 4.5.2 and they took my admin rights away) I checked with @dmueller3000 but he also noted the same issue.

**Comment by bogdanni** [comment]
This is known issue due to the server migration. The timeline data server could not be recovered in the new software context.

The timelines will be re-instated in a new implementation, using modern server software.
Apologies for the interruption of service, will notify here when it will be available. At that moment, it will require a new version of JHV.

**Comment by bogdanni** [comment]
A new HAPI server was installed at ROB. It is fed from the internal timelines databases and JHV version 4.7.0 was updated to use it as source for timeline data. 
Hopefully you will be allowed to update the JHV version, Piers.
