### ISSUE TITLE
Enhancement : parameter server in request.json ? 

### ISSUE THREAD

**Issue by MedocIAS** [Helioviewer-Project/JHelioviewer-SWHV#72]
Hello,

Can you please add a parameter server?
So we will be able to specify a targeted server using the following :

java -jar JHelioviewer.jar -request ./request.json 

with a request.json containing :
 {
        "server" : "IAS", 
        "observatory": "SDO",
        "startTime": "2012-03-06 12:00:00",
        "endTime": "2012-03-06 20:00:00",
        "cadence": 3600,
        "dataset": "AIA 304"
}

Best regards, 
P. 
IAS

**Comment by ebuchlin** [comment]
Some context about the use case: when started, with or without -request, JHV assumes that the server to use is the default server. When a user provides a request.json asking for example for Kanzelhöhe Hα (only at ROB), what is the behavior of JHV? (I cannot test because I don't have the observatory/dataset strings for that). Does it say that there is no data? Does it fall back to the ROB server? Adding a "server" field in the request.json as proposed by @MedocIAS could help, but maybe the client could do something more intelligent (like a fallback).

**Comment by bogdanni** [comment]
Note also that this request file may be remote (HTTP) and it is now loaded after all servers responded.
Consequently, if one server does not respond, the load will be delayed which may be unexpected. That is the reason for which the default server was used. At least the user could change the default server and retry.
